baseURL = "https://onebitwonders.com"
title = "Zach Thornton"
theme = "m10c"
paginate = 10

[params]
  author = "Zach Thornton"
  description = "Data Engineer @ Audley Travel"
  [[params.social]]
    name = "github"
    url = "https://github.com/zThorn"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/zachthornton"
  [[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/zThorn"
  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  [params.style]
    darkestColor = "#3A1616"
    darkColor = "#212121"
    lightColor = "#f5e3e0"
    lightestColor = "#C9C9C9"
    primaryColor = "#C9C9C9"
  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
